# -*- coding: utf-8 -*-
"""Sinhala letter recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKZIfV8ArwBHnJX5eqeOePk1wxVQS6AQ

get folder names
"""

import os
import numpy as np

data_path="/content/drive/MyDrive/dataset"
categories = os.listdir(data_path)
print(categories)
labels=[i for i in range(len(categories))]
category_dict={'a':0,'ae':1,'e':2,'u':3}

"""get images from folders"""

import cv2 as opencv
from google.colab.patches import cv2_imshow

data=[]
target=[]

for category in categories:
  folder_path=os.path.join(data_path,category)
  for img in os.listdir(folder_path):
    img_path=os.path.join(folder_path,img)
    img=opencv.imread(img_path,0)
    # cv2_imshow(img)
    img=opencv.resize(img,(8,8))
    # cv2_imshow(img)
    data.append(img)
    target.append(category_dict[category])

print(len(data))

"""flat the images"""

data=np.array(data)
target=np.array(target)

data=data.reshape(data.shape[0],data.shape[1]*data.shape[2])
print(data[1])

np.save('data',data)
np.save('target',target)

"""load data from saved files"""

data=np.load('data.npy')
target=np.load('target.npy')

"""split the data as test and training"""

from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.2)
print(train_data.shape)
print(train_target.shape)
print(test_data.shape)
print(test_target.shape)

"""**train** data"""

from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier()
model.fit(train_data,train_target)

"""test the model"""

predicted_data=model.predict(test_data)
print(predicted_data)

"""check accuracy"""

from sklearn.metrics import accuracy_score

accuracy=accuracy_score(test_target,predicted_data)
print(accuracy)

"""save the model"""

import joblib

joblib.dump(model,'sinhala-character-knn.sav')

